version: '3'

services:
  java-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./target:/data
    networks:
      - my_network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./data:/data
    networks:
      - my_network
    command: ["python", "app.py"]

networks:
  my_network:
    driver: bridge
